import React from 'react';

export const metadata = {
    title: 'About | Next App',
    description: 'Generated by create next app',
  }
const Homepage = () => {
    return (
        <div>
            Homepage
        </div>
    );
};

export default Homepage;