import React from 'react';

export const metadata = {
    title: 'Add Products |Dashboard | Next App',
    description: 'Generated by create next app',
  }
const AddProductsPage = () => {
    return (
        <div>
            AddProductsPage
        </div>
    );
};

export default AddProductsPage;