import React from 'react';
export const metadata = {
    title: 'Manage Products|Dashboard | Next App',
    description: 'Generated by create next app',
  }
const ManageProductsPage = () => {
    return (
        <div>
            ManageProducts
        </div>
    );
};

export default ManageProductsPage;