import React from 'react';
export const metadata = {
    title: 'Dashboard | Next App',
    description: 'Generated by create next app',
  }
const DashBoardLayout = ({children}) => {
    return (
        <div>
           <div>SideBar</div>
           {children} 
        </div>
    );
};

export default DashBoardLayout;